name: test and deploy

on:
  push:
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        name: unit tests
        run: ./gradlew test
#  android_test:
#    runs-on: macos-latest
#    steps:
#      - uses: action/checkout@v2
#
#
#        name: Instrumentation tests
#         - uses: reactivecircus/android-emulator-runner@v2
#          with:
#          api-level: 29
#          script: ./gradlew connectedAndroidTest